title: Parker Booth
logo: "/images/Real Headshot.png" # your photo (or logo) here
 
description: >
  <p>Hello! My name is Parker Booth, and I am a data scientist with an emphasis on statistics analysis and a passion for sports analytics.</p>

  <p>This portfolio showcases projects completed in both my undergraduate and graduate studies.</p>

  <p><a href="https://github.com/ParkerBooth/Sports-Analyst-Portfolio/blob/main/Parker%20Booth%20Resume.pdf">View My Resume</a></p>

  <p><a href="https://www.linkedin.com/in/parker-booth-26b81b237/">View My LinkedIn Profile</a></p>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
